ladid_from_gate_dc2 = "SELECT ladid FROM x WHERE plnamtor = :str AND ladfsrsta = 200 AND rownum = 1"
tenam_from_place_and_ladid_dc2 = "select tenam from x where lttnam = 'EURO' and plnam like :str and ladid = :str2 and rownum = 1"
tenam_from_pallet_dc2 = "SELECT te.tenam FROM x te JOIN x tte ON te.tenamtrg = tte.tenam where tte.tenam = :str and rownum = 1"
tenam_count_from_pallet_dc2 = "SELECT DISTINCT count(te.tenam) FROM x te JOIN x tte ON te.tenamtrg = tte.tenam WHERE tte.tenam = :str"
tenam_count_from_plnam_dc2 = "SELECT DISTINCT count(te.tenam) FROM x te JOIN x tte ON te.tenamtrg = tte.tenam WHERE tte.plnam like :str"
tenam_on_place_with_rowid_dc2 = "SELECT tenam FROM (SELECT te.tenam, ROWNUM AS rnum FROM x te JOIN x TTE ON te.tenamtrg = tte.tenam WHERE tte.plnam LIKE :str) WHERE rnum = :num"
ladid_from_gate_dc4 = "SELECT ladid FROM y WHERE plnamtor = :str AND ladfsrsta = 200 AND rownum = 1"
tenam_from_place_and_ladid_dc4 = "select tenam from y where lttnam = 'EURO' and plnam like :str and ladid = :str2 and rownum = 1"
tenam_from_pallet_dc4 = "SELECT te.tenam FROM y te JOIN y tte ON te.tenamtrg = tte.tenam where tte.tenam = :str and rownum = 1"
tenam_count_from_pallet_dc4 = "SELECT DISTINCT count(te.tenam) FROM y te JOIN y tte ON te.tenamtrg = tte.tenam WHERE tte.tenam = :str"
tenam_count_from_plnam_dc4 = "SELECT DISTINCT count(te.tenam) FROM y te JOIN y tte ON te.tenamtrg = tte.tenam WHERE tte.plnam like :str"
tenam_on_place_with_rowid_dc4 = "SELECT tenam FROM (SELECT te.tenam, ROWNUM AS rnum FROM y te JOIN y TTE ON te.tenamtrg = tte.tenam WHERE tte.plnam LIKE :str) WHERE rnum = :num"
